"""
Constants and configuration for Aayura Healthcare Application
Includes translations, colors, and API configuration
"""
from deep_translator import GoogleTranslator

# API Configuration
BACKEND_URL = "http://localhost:8000"

# Color Palette
COLORS = {
    'primary': '#3b82f6',
    'primary_light': '#60a5fa',
    'primary_dark': '#2563eb',
    'success': '#10b981',
    'warning': '#f59e0b',
    'danger': '#ef4444',
    'bg_dark': '#0f172a',
    'bg_light': '#f8fafc',
    'text_dark': '#1e293b',
    'text_light': '#64748b',
    'border': '#e2e8f0',
}

# Language Translations
TRANSLATIONS = {
    'en': {
        'app_name': 'Aayura',
        'app_subtitle': 'Disease Outbreak Forecasting & Management',
        'welcome_back': 'Welcome Back',
        'username': 'Username',
        'password': 'Password',
        'login': 'Login',
        'signup': 'Sign Up',
        'demo_credentials': 'Demo Credentials',
        'create_account': 'Create Your Account',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'confirm_password': 'Confirm Password',
        'state': 'State',
        'district': 'District',
        'role': 'Role',
        'create': 'Create Account',
        'back': 'Back',
        'logout': 'Logout',
        'outbreak_management': 'Outbreak Management Assistant',
        'ask_question': 'Ask a question or request guidance',
        'message': 'Message',
        'send': 'Send',
        'service_requests': 'Service Requests',
        'request_item': 'Request Item',
        'request_details': 'Details',
        'submit_request': 'Submit Request',
        'pending_requests': 'Pending Requests',
        'escalate': 'Escalate',
        'no_pending': 'No pending requests',
        'authenticating': 'Authenticating...',
        'invalid_credentials': 'Invalid credentials',
        'please_enter_both': 'Please enter both username and password',
        'creating_account': 'Creating account...',
        'account_created': 'Account created!',
        'passwords_dont_match': "Passwords don't match",
        'password_min_6': 'Password must be at least 6 characters',
        'please_fill_all': 'Please fill all fields',
        'loading_stats': 'Loading outbreak statistics...',
        'no_data': 'No outbreak data available at the moment.',
        'outbreak_status': 'Outbreak Status',
        'disease': 'Disease',
        'expected_cases': 'Expected Cases',
        'male_cases': 'Male Cases',
        'female_cases': 'Female Cases',
        'children_0_5': 'Children (0-5)',
        'youth_5_18': 'Youth (5-18)',
        'adults_18_60': 'Adults (18-60)',
        'elderly_60_plus': 'Elderly (60+)',
        'select_language': 'Select Language',
        'no_actions': 'No actions available',
        'unable_to_generate': 'Unable to generate actions at this time',
        'request_submitted': 'Request submitted!',
        'select_state_first': 'Select state first',
        'failed_to_create': 'Failed to create account',
        'no_requests_yet': 'No requests yet',
        'details': 'Details',
        'request_item_placeholder': 'e.g., Medical Supplies',
        'details_placeholder': 'Describe your request',
        'please_fill_fields': 'Please fill all fields',
        'level': 'Level',
        'escalated_to_level': 'Escalated to level',
        'unable_to_escalate': 'Unable to escalate',
        'no_pending_requests': 'No pending requests',
    },
    'hi': {
        'app_name': 'आयुर',
        'app_subtitle': 'रोग प्रकोप पूर्वानुमान और प्रबंधन',
        'welcome_back': 'स्वागत है',
        'username': 'उपयोगकर्ता नाम',
        'password': 'पासवर्ड',
        'login': 'लॉगिन',
        'signup': 'साइन अप',
        'demo_credentials': 'डेमो क्रेडेंशियल्स',
        'create_account': 'अपना खाता बनाएं',
        'first_name': 'पहला नाम',
        'last_name': 'अंतिम नाम',
        'confirm_password': 'पासवर्ड की पुष्टि करें',
        'state': 'राज्य',
        'district': 'जिला',
        'role': 'भूमिका',
        'create': 'खाता बनाएं',
        'back': 'वापस जाएं',
        'logout': 'लॉगआउट',
        'outbreak_management': 'प्रकोप प्रबंधन सहायक',
        'ask_question': 'कोई प्रश्न पूछें या मार्गदर्शन माँगें',
        'message': 'संदेश',
        'send': 'भेजें',
        'service_requests': 'सेवा अनुरोध',
        'request_item': 'अनुरोध आइटम',
        'request_details': 'विवरण',
        'submit_request': 'अनुरोध भेजें',
        'pending_requests': 'लंबित अनुरोध',
        'escalate': 'बढ़ाएं',
        'no_pending': 'कोई लंबित अनुरोध नहीं',
        'authenticating': 'प्रमाणीकरण जारी है...',
        'invalid_credentials': 'अमान्य साख',
        'please_enter_both': 'कृपया उपयोगकर्ता नाम और पासवर्ड दोनों दर्ज करें',
        'creating_account': 'खाता बना रहे हैं...',
        'account_created': 'खाता बनाया गया!',
        'passwords_dont_match': 'पासवर्ड मेल नहीं खाते',
        'password_min_6': 'पासवर्ड कम से कम 6 वर्ण होना चाहिए',
        'please_fill_all': 'कृपया सभी फ़ील्ड भरें',
        'loading_stats': 'प्रकोप सांख्यिकी लोड हो रही है...',
        'no_data': 'इस समय कोई प्रकोप डेटा उपलब्ध नहीं है।',
        'outbreak_status': 'प्रकोप स्थिति',
        'disease': 'रोग',
        'expected_cases': 'अपेक्षित मामले',
        'male_cases': 'पुरुष मामले',
        'female_cases': 'महिला मामले',
        'children_0_5': 'बच्चे (0-5)',
        'youth_5_18': 'युवा (5-18)',
        'adults_18_60': 'वयस्क (18-60)',
        'elderly_60_plus': 'बुजुर्ग (60+)',
        'select_language': 'भाषा चुनें',
        'no_actions': 'कोई कार्रवाई उपलब्ध नहीं',
        'unable_to_generate': 'इस समय कार्रवाई उत्पन्न करने में असमर्थ',
        'request_submitted': 'अनुरोध प्रस्तुत!',
        'select_state_first': 'पहले राज्य चुनें',
        'failed_to_create': 'खाता बनाने में विफल',
        'no_requests_yet': 'अभी कोई अनुरोध नहीं',
        'details': 'विवरण',
        'request_item_placeholder': 'जैसे, चिकित्सा आपूर्ति',
        'details_placeholder': 'अपने अनुरोध का वर्णन करें',
        'please_fill_fields': 'कृपया सभी फ़ील्ड भरें',
        'level': 'स्तर',
        'escalated_to_level': 'स्तर तक बढ़ाया गया',
        'unable_to_escalate': 'बढ़ाने में असमर्थ',
        'no_pending_requests': 'कोई लंबित अनुरोध नहीं',
    },
    'bn': {
        'app_name': 'আয়ুরা',
        'app_subtitle': 'রোগ প্রাদুর্ভাব পূর্বাভাস এবং ব্যবস্থাপনা',
        'welcome_back': 'স্বাগতম',
        'username': 'ব্যবহারকারীর নাম',
        'password': 'পাসওয়ার্ড',
        'login': 'লগইন করুন',
        'signup': 'সাইন আপ করুন',
        'demo_credentials': 'ডেমো সংজ্ঞাপত্র',
        'create_account': 'আপনার অ্যাকাউন্ট তৈরি করুন',
        'first_name': 'প্রথম নাম',
        'last_name': 'পরিবার নাম',
        'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
        'state': 'রাজ্য',
        'district': 'জেলা',
        'role': 'ভূমিকা',
        'create': 'অ্যাকাউন্ট তৈরি করুন',
        'back': 'ফিরে যান',
        'logout': 'লগআউট করুন',
        'outbreak_management': 'প্রাদুর্ভাব ব্যবস্থাপনা সহায়ক',
        'ask_question': 'একটি প্রশ্ন জিজ্ঞাসা করুন বা নির্দেশনা চান',
        'message': 'বার্তা',
        'send': 'পাঠান',
        'service_requests': 'সেবা অনুরোধ',
        'request_item': 'অনুরোধের আইটেম',
        'request_details': 'বিবরণ',
        'submit_request': 'অনুরোধ জমা দিন',
        'pending_requests': 'মুলতুবি অনুরোধ',
        'escalate': 'উন্নীত করুন',
        'no_pending': 'কোন মুলতুবি অনুরোধ নেই',
        'authenticating': 'প্রমাণীকরণ চলছে...',
        'invalid_credentials': 'অবৈধ শংসাপত্র',
        'please_enter_both': 'দয়া করে ব্যবহারকারীর নাম এবং পাসওয়ার্ড উভয়ই প্রবেশ করুন',
        'creating_account': 'অ্যাকাউন্ট তৈরি করছি...',
        'account_created': 'অ্যাকাউন্ট তৈরি হয়েছে!',
        'passwords_dont_match': 'পাসওয়ার্ড মেলে না',
        'password_min_6': 'পাসওয়ার্ড কমপক্ষে 6 অক্ষর হতে হবে',
        'please_fill_all': 'দয়া করে সমস্ত ক্ষেত্র পূরণ করুন',
        'loading_stats': 'প্রাদুর্ভাব পরিসংখ্যান লোড করছি...',
        'no_data': 'এই মুহূর্তে কোন প্রাদুর্ভাব ডেটা উপলব্ধ নেই।',
        'outbreak_status': 'প্রাদুর্ভাব অবস্থা',
        'disease': 'রোগ',
        'expected_cases': 'প্রত্যাশিত ক্ষেত্রে',
        'male_cases': 'পুরুষ ক্ষেত্রে',
        'female_cases': 'মহিলা ক্ষেত্রে',
        'children_0_5': 'শিশু (0-5)',
        'youth_5_18': 'তরুণ (5-18)',
        'adults_18_60': 'প্রাপ্তবয়স্ক (18-60)',
        'elderly_60_plus': 'বয়স্ক (60+)',
        'select_language': 'ভাষা নির্বাচন করুন',
        'no_actions': 'কোন পদক্ষেপ উপলব্ধ নেই',
        'unable_to_generate': 'এই মুহূর্তে পদক্ষেপ তৈরি করতে অক্ষম',
        'request_submitted': 'অনুরোধ জমা দেওয়া হয়েছে!',
        'select_state_first': 'প্রথমে রাজ্য নির্বাচন করুন',
        'failed_to_create': 'অ্যাকাউন্ট তৈরি করতে ব্যর্থ',
        'no_requests_yet': 'এখনো কোনো অনুরোধ নেই',
        'details': 'বিবরণ',
        'request_item_placeholder': 'যেমন, চিকিৎসা সরবরাহ',
        'details_placeholder': 'আপনার অনুরোধ বর্ণনা করুন',
        'please_fill_fields': 'দয়া করে সমস্ত ক্ষেত্র পূরণ করুন',
        'level': 'স্তর',
        'escalated_to_level': 'স্তরে উন্নীত করা হয়েছে',
        'unable_to_escalate': 'উন্নীত করতে অক্ষম',
        'no_pending_requests': 'কোন মুলতুবি অনুরোধ নেই',
    },
    'ta': {
        'app_name': 'ஆயுர',
        'app_subtitle': 'நோய் பெருக்கம் முன்னறிவிப்பு மற்றும் நிர்வாகம்',
        'welcome_back': 'வரவேற்கிறோம்',
        'username': 'பயனர் பெயர்',
        'password': 'கடவுசொல்',
        'login': 'உள்நுழைக',
        'signup': 'பதிவு செய்',
        'demo_credentials': 'ஆDemo சான்றுகள்',
        'create_account': 'உங்கள் கணக்கை உருவாக்கவும்',
        'first_name': 'முதல் பெயர்',
        'last_name': 'கடைசி பெயர்',
        'confirm_password': 'கடவுசொல்லை உறுதிப்படுத்தவும்',
        'state': 'மாநிலம்',
        'district': 'மாவட்டம்',
        'role': 'பங்கு',
        'create': 'கணக்கை உருவாக்கவும்',
        'back': 'பின்னோக்கு',
        'logout': 'வெளிநிறுத்தவும்',
        'outbreak_management': 'நோய் பெருக்கம் நிர்வாგ உதவியாளர்',
        'ask_question': 'கேள்வியைக் கேளுங்கள் அல்லது வழிகாட்டல் கேளுங்கள்',
        'message': 'செய்தி',
        'send': 'அனுப்பவும்',
        'service_requests': 'சேவை கோரிக்கைகள்',
        'request_item': 'கோரிக்கையின் உருப்படி',
        'request_details': 'விவரங்கள்',
        'submit_request': 'கோரிக்கை சமர்ப்பிக்க',
        'pending_requests': 'நிலுவையில் உள்ள கோரிக்கைகள்',
        'escalate': 'உயர்த்துங்கள்',
        'no_pending': 'நிலுவையில் உள்ள கோரிக்கைகள் இல்லை',
        'authenticating': 'சான்றளிக்கிறது...',
        'invalid_credentials': 'செல்லாத சான்றுகள்',
        'please_enter_both': 'பயனர் பெயர் மற்றும் கடவுசொல் இரண்டையும் உள்ளிடவும்',
        'creating_account': 'கணக்கை உருவாக்குகிறது...',
        'account_created': 'கணக்கை உருவாக்கியது!',
        'passwords_dont_match': 'கடவுசொற்கள் பொருந்தவில்லை',
        'password_min_6': 'கடவுசொல் குறைந்தது 6 எழுத்துக்கள் இருக்க வேண்டும்',
        'please_fill_all': 'நன்றி, அனைத்து புலங்களையும் நிரப்பவும்',
        'loading_stats': 'நோய் பெருக்கம் புள்ளிவிவரங்களை ஏற்றுகிறது...',
        'no_data': 'இப்போது நோய் பெருக்கம் தரவு கிடைக்கவில்லை.',
        'outbreak_status': 'நோய் பெருக்கம் நிலை',
        'disease': 'நோய்',
        'expected_cases': 'எதிர்பார்த்த வழக்குகள்',
        'male_cases': 'ஆண் வழக்குகள்',
        'female_cases': 'பெண் வழக்குகள்',
        'children_0_5': 'குழந்தைகள் (0-5)',
        'youth_5_18': 'இளைஞர்கள் (5-18)',
        'adults_18_60': 'வயதுவந்தோர் (18-60)',
        'elderly_60_plus': 'பெரியவர்கள் (60+)',
        'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
        'no_actions': 'கிடைக்கக்கூடிய நடவடிக்கைகள் இல்லை',
        'unable_to_generate': 'இப்போது நடவடிக்கைகளை உருவாக்க முடியாது',
        'request_submitted': 'கோரிக்கை சமர்ப்பிக்கப்பட்டுவிட்டது!',
        'select_state_first': 'முதலில் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
        'failed_to_create': 'கணக்கை உருவாக்க தோல்வியடைந்தது',
        'no_requests_yet': 'இதுவரை கோரிக்கைகள் இல்லை',
        'details': 'விவரங்கள்',
        'request_item_placeholder': 'எ.கா, மருத்துவ உபகரணங்கள்',
        'details_placeholder': 'உங்கள் கோரிக்கையை விவரிக்கவும்',
        'please_fill_fields': 'நன்றி, அனைத்து புலங்களையும் நிரப்பவும்',
        'level': 'நிலை',
        'escalated_to_level': 'நிலைக்கு உயர்த்தப்பட்டது',
        'unable_to_escalate': 'உயர்த்த முடியாது',
        'no_pending_requests': 'நிலுவையில் உள்ள கோரிக்கைகள் இல்லை',
    }
}


# Helper functions
def get_text(key: str, language: str = 'en') -> str:
    """Get translated text for a given key in the specified language"""
    return TRANSLATIONS.get(language, {}).get(key, TRANSLATIONS['en'].get(key, key))


def translate_to_english(text: str, source_lang: str) -> str:
    """Convert user input to English for API calls"""
    if source_lang == 'en':
        return text
    return text


def translate_api_response(text_to_translate: str, target_language:str) -> str:
    """
        Translates text using Google Translator via deep_translator.

        Args:
            text_to_translate (str): The text to translate.
            target_language (str): The target language name (e.g., 'spanish', 'german').

        Returns:
            str: The translated text.
    """
    try:
        translated_text = GoogleTranslator(source='auto', target=target_language).translate(text_to_translate)
        return translated_text
    except Exception as e:
        return f"An error occurred: {e}"

